language: java

jdk:
- oraclejdk8

sudo: required
services:
  - docker

env:
- SUDO_PASSWORD=""

install: travis_wait mvn install -Pdocker-build-only -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -Dtest-profile=docker -B