#!/usr/bin/env bash

docker run --privileged -v /dev:/host/dev -v ${HOME}/.smolok/downloads:/root/.smolok/downloads \
  -v /var/smolok/spark/jobs:/var/smolok/spark/jobs \
  -v /var/run/docker.sock:/run/docker.sock -it smolok/cmd:0.0.0-SNAPSHOT "$@"